### ISSUE TITLE
404's fetching actions.json reported strangely

### ISSUE THREAD

**Issue by djmitche** [mozilla/treeherder#5617]
If a decision task's `actions.json` is not found, for example because the task exists in a different TC deployment or has expired, then TH seems to say "Wrong version of actions.json, unable to continue" which is a bit misleading.  I suspect this is happening because the fetch is not converting the 404 into a rejected Promise, but rather returning it as a regular response.  The code in `ui/models/taskcluster.js` then looks for `version` in this response, doesn't find it, and gives this error.

**Comment by armenzg** [comment]
This issue cannot be completely tested by contributors unless you can sign in with [Auth0](https://sso.mozilla.com)

Steps to reproduce:

* https://treeherder.mozilla.org/#/jobs?repo=mozilla-release&revision=964ff679f60d09e43df069a49f48500d1010e13d
* Sign in with your LDAP
* Click on 'Add new jobs'

I've actually received a different error message.

You will get this message instead of a prompt:
> `Error fetching runnable jobs: Failed to fetch task ID (TypeError: can't convert undefined to object)`

**Comment by armenzg** [comment]
I will close this as I assume it does not happen easily. Please re-open if it's still happening.
